# Site settings
title: Index
#email: your-email@domain.com
description: "Things, stuff, random stuff, arbitrary stuff and things."
#twitter_username: MyFakeAcc
#github_username: Argon-
excerpt_separator: "<!-- more -->"

# Build settings
safe: true
destination: _site_remote
#baseurl: "http://localhost/~Julian/www/Index/_site"
markdown: kramdown
highlighter: pygments
encoding: utf-8
permalink: /:year/:month/:day/:title/
