# Site settings
title: Index
#email: your-email@domain.com
description: "Things, stuff, random stuff, arbitrary stuff and things."
#baseurl: "http://localhost/~Julian/www/Index/_site" 
#twitter_username: MyFakeAcc
#github_username: Argon-
highlighter: pygments
excerpt_separator: "<!-- more -->"

# Build settings
markdown: kramdown
encoding: utf-8
permalink: pretty
